### ISSUE TITLE
Migrate to robotology? 

### ISSUE THREAD

**Issue by traversaro** [robotology/forcetorque-yarp-devices#12]
This repo is widely used for our experiements, I think it would make sense to move it to the robotology organisation . What do you think @fjandrad ?

**Comment by fjandrad** [comment]
I agree, is there something to change for making it compliant with robotology instead of robotlogy-playground?

**Comment by traversaro** [comment]
No, I just need to move it.

**Comment by traversaro** [comment]
Done.
