### ISSUE TITLE
Discuss and decide repo management

### ISSUE THREAD

**Issue by traversaro** [robotology/forcetorque-yarp-devices#18]
After Francisco left the lab, this repo does not have a clear maintainer. We should find one. 

cc @DanielePucci

**Comment by traversaro** [comment]
Or, if no one is using this repo, we could just deprecate it and move it to https://github.com/robotology-legacy .

**Comment by DanielePucci** [comment]
> Or, if no one is using this repo, we could just deprecate it and move it to https://github.com/robotology-legacy .

Probably this is a possibility: I have no memory of usage for this repo. @robotology/iit-dynamic-interaction-control please tell us in the case there is an active user

**Comment by traversaro** [comment]
I think the only relevant use case is to access the AMTI force plates: probably also that can be just migrate to the collection of AndySuit-related devices repo (if there is still plan to open it) and then archive this repo.

**Comment by DanielePucci** [comment]
CC @claudia-lat @Yeshasvitvs @lrapetti

**Comment by Yeshasvitvs** [comment]
> we could just deprecate it and move it to https://github.com/robotology-legacy .

This repo was referred in the report given during Xsens technology transfer for installing FTShoe drivers. So if we decide to archive this to robotology-legacy, we need to update some of the AnDy project partners like Xsens and possible Inria about the change in the location for this repository or the new location of the code for FTShoe drivers

**Comment by traversaro** [comment]
If that is a concrete concern, then we should have at least some basic compilation CI working on the repo to make sure that it is actually compiling (at least). We can also just remove from this repo all the devices that are not used anymore, and just keep the devices that we use, possibility changing the name of the repo to be more descriptive.

**Comment by DanielePucci** [comment]
Please @Yeshasvitvs align F2F with @traversaro so as to find an agreement on how to proceed, thanks

**Comment by Yeshasvitvs** [comment]
Actions Points after meeting between @traversaro and @Yeshasvitvs  

- Identify drivers that are no longer used by any users at [DIC](https://github.com/dic-iit) e.g. optoforce and ATI 
- Remove identified drivers from the repo, and move them to https://github.com/robotology-legacy. Update the readme of the repo with references to the new location
- May be rename the repo name to something more relevant (TBD)
- Add a maintainer who will take care of the above steps and add CI to ensure the drivers that are actively under use (e.g. ftShoe and ftNode) are upto date with the rest of the robotology code the drivers depend on

@fjandrad please let us know what you think about the above points. Thanks. 

I will open new issue(s) to handle the above action points

CC @claudia-lat @lrapetti

**Comment by traversaro** [comment]
Thanks @Yeshasvitvs, feel free to close this issue then.

**Comment by Yeshasvitvs** [comment]
> Identify drivers that are no longer used by any users at DIC e.g. optoforce and ATI

The main drivers that are currently used by members of @robotology/iit-dynamic-interaction-control are:

- [ftShoe](https://github.com/robotology/forcetorque-yarp-devices/tree/master/ftShoe)
- [ftNode](https://github.com/robotology/forcetorque-yarp-devices/tree/master/ftNode)
- [amti](https://github.com/robotology/forcetorque-yarp-devices/tree/master/amti)

The following drivers can be moved to https://github.com/robotology-legacy

- AME
- ATI_Ethernet
- optoforce
- ftShoeUdpWrapper

@traversaro if you agree we can move then 

CC @fjandrad @francesco-romano @lucaTagliapietra

**Comment by traversaro** [comment]
> After Francisco left the lab, this repo does not have a clear maintainer. We should find one.

Fixed by https://github.com/robotology/forcetorque-yarp-devices/pull/27, congrats @RiccardoGrieco . The issue contains also generic cleanup suggestions that it may be worth to follow, but the main point of the issue is fixed.
