### ISSUE TITLE
Cleanup use of YARP deprecated methods

### ISSUE THREAD

**Issue by traversaro** [robotology/forcetorque-yarp-devices#28]
YARP deprecated methods such as `asDouble` are used in the codebase, for example in https://github.com/robotology/forcetorque-yarp-devices/blob/e8c5e3a174c6720e5e6bc548119438a6abb95d90/ftShoe/ftshoeDriver.cpp#L127 . That code will not compile once https://github.com/robotology/yarp/pull/2833 is merged.

**Comment by traversaro** [comment]
fyi @RiccardoGrieco

**Comment by RiccardoGrieco** [comment]
PR #29 was merged, closing this issue.

**Comment by traversaro** [comment]
Thanks @RiccardoGrieco !
